use_frameworks!

platform :ios, '9.0'

target 'YCAssistivePlugin_Example' do
  pod 'YCAssistivePlugin', :path => '../'

  target 'YCAssistivePlugin_Tests' do
    inherit! :search_paths

    
  end
end


#pod 'YCNetworking', :path=> '../../YCNetworking'
